#pragma once

//ability
#define ABILITY_MANIPULATE_TILE "ManipulateTile"
#define ABILITY_HEAL "Heal"
#define ABILITY_FIGHT "Fight"
#define ABILITY_SUMMON_UNIT "SummonUnit"
#define ABILITY_SHOOT "Shoot"
#define ABILITY_SABOTAGE "Sabotage"
#define ABILITY_BUILD_WALL "Build the Wall"
#define ABILITY_ENCOURAGE "Encourage"
#define ABILITY_QUICK_SHOOT "Quick Shoot"
#define ABILITY_SLAY "Slay"
#define ABILITY_DODGE "Dodge"
#define ABILITY_BLAST "Blast"
#define ABILITY_BURN "Burn"
#define ABILITY_FIRE_DANCE "Fire Dance"
#define ABILITY_FIRE "Fire"
#define ABILITY_LOAD "Load"
#define ABILITY_VOLLEY "Volley"
#define ABILITY_ARM "Arm"
#define ABILITY_THE_LIGHT "The Light"
#define ABILITY_POWER_OF_MONEY "Power of Money"
#define ABILITY_INVEST "Invest"
#define ABILITY_GOLD_RUSH "Gold Rush"
//ability-action
#define ACTION_MOVE "Move"
#define ACTION_JOIN "Join"

//status
#define STATUS_ENCOURAGE "Status_Encourage"
#define STATUS_LV "Status_LV"
#define STATUS_PRIEST_LV3 "Status_Priest_LV3"
#define STATUS_ARCHER_LV3 "Status_Archer_LV3"
#define STATUS_DUELIST_LV3 "Status_Duelist_LV3"
#define STATUS_DODGE "Status_Dodge"
#define STATUS_TEMP_CHANGE "Status_Temp_Change"
#define STATUS_AD_CHANGE "Status_AD_Change"
#define STATUS_LOAD "Status_Load"
#define STATUS_SHIELD "Status_Shield"